using System;

namespace CrashCatcher
{
    internal static class CrashCatcherSourceLists
    {
        internal static readonly string[] Ordered =
        {
            "Source/Settings",
            "Source/Patches",
            "Source/Lists"
        };
    }

    internal static class CrashHandoffMarkers
    {
        internal static readonly string[] Ordered =
        {
            "CrashCrashHandler.Latch",
            "CrashCatcherHooks.Install",
            "CrashCatcherHooks.OnFirstChanceException",
            "CrashCatcherHooks.OnUnhandledException",
            "CrashCatcherHooks.OnLogMessageReceivedThreaded",
            "CrashCatcherHooks.TryLatchPendingTextureWarning",
            "CrashCatcherHooks.OnWantsToQuit"
        };
    }

    internal static class TickCapturePriority
    {
        internal static readonly string[] Ordered =
        {
            "Verse.Root.Update",
            "Verse.Game.UpdatePlay",
            "LongEventHandler.QueueLongEvent",
            "LongEventHandler.ExecuteWhenFinished",
            "Verse.Map.MapUpdate",
            "Verse.DynamicDrawManager.DrawDynamicThings",
            "Verse.PawnRenderer.DynamicDrawPhaseAt",
            "Verse.Thing.DoTick",
            "Verse.MapComponent.MapComponentTick",
            "Verse.AI.JobDriver.DriverTick",
            "Verse.AI.JobDriver.ReadyForNextToil",
            "Verse.AI.JobDriver.TryMakePreToilReservations",
            "Verse.ThingComp.Initialize",
            "Verse.ThingComp.PostExposeData",
            "Verse.ThingComp.PostMapInit",
            "Verse.ThingComp.PostSpawnSetup",
            "Verse.ThingComp.PostDeSpawn",
            "Verse.ThingComp.PostDestroy",
            "Verse.ThingComp.PostPostMake",
            "RimWorld.Planet.WorldObjectComp.Initialize",
            "RimWorld.Planet.WorldObjectComp.PostExposeData",
            "RimWorld.Planet.WorldObjectComp.PostPostRemove",
            "RimWorld.Planet.WorldObjectComp.PostCaravanFormed",
            "RimWorld.Planet.WorldObjectComp.PostDestroy",
            "RimWorld.Planet.WorldObjectComp.PostMyMapRemoved",
            "RimWorld.Planet.WorldObjectComp.PostMapGenerate",
            "RimWorld.Planet.WorldObject.PostExposeData",
            "RimWorld.Planet.WorldObject.PostMake",
            "RimWorld.Planet.WorldObject.PostAdd",
            "RimWorld.Planet.WorldObject.PostRemove",
            "RimWorld.Planet.WorldObject.Destroy",
            "Verse.ThingOwner.DoTick",
            "Verse.ThingComp.CompTick",
            "Verse.ThingComp.CompTickInterval",
            "Verse.ThingComp.CompTickRare",
            "Verse.ThingComp.CompTickLong",
            "RimWorld.Planet.WorldObjectComp.CompTick",
            "RimWorld.Planet.WorldObjectComp.CompTickInterval",
            "Verse.LongEventHandler.QueueLongEvent",
            "Verse.LongEventHandler.ExecuteWhenFinished",
            "Map.MapPreTick",
            "TickManager",
            "DateNotifierTick",
            "Scenario.TickScenario",
            "World.WorldTick",
            "StoryWatcherTick",
            "GameEndTick",
            "StorytellerTick",
            "TaleManagerTick",
            "QuestManagerTick",
            "World.WorldPostTick",
            "Map.MapPostTick() for every map",
            "HistoryTick",
            "GameComponentUtility.GameComponentTick",
            "LetterStackTick",
            "AutosaverTick",
            "optional hourly screenshot capture",
            "FilthMonitorTick",
            "TransportShipManager.ShipObjectsTick",
            "TickManager.TickManagerUpdate",
            "TickList.Tick",
            "GameComponentUtility",
            "WorldComponentUtility",
            "Application.logMessageReceivedThreaded",
            "AppDomain.CurrentDomain.UnhandledException",
            "AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve",
            "TickManager.DoSingleTick already patched",
            "TickList.Tick for normal/rare/long buckets",
            "Find.DateNotifier.DateNotifierTick",
            "Find.StoryWatcher.StoryWatcherTick",
            "Find.GameEnder.GameEndTick",
            "Find.Storyteller.StorytellerTick",
            "Find.TaleManager.TaleManagerTick",
            "Find.QuestManager.QuestManagerTick",
            "Find.History.HistoryTick",
            "Find.LetterStack.LetterStackTick",
            "Find.Autosaver.AutosaverTick",
            "FilthMonitor.FilthMonitorTick",
            "MapComponentUtility.MapComponentUpdate",
            "MapComponentUtility.FinalizeInit",
            "MapComponentUtility.MapGenerated",
            "MapComponentUtility.MapRemoved",
            "World.WorldUpdate",
            "WorldComponentUtility.WorldComponentTick",
            "WorldComponentUtility.WorldComponentUpdate",
            "WorldComponentUtility.FinalizeInit",
            "Game.UpdateEntry",
            "Game.FinalizeInit",
            "Game.LoadGame",
            "Game.InitNewGame",
            "GameComponentUtility.GameComponentUpdate",
            "GameComponentUtility.FinalizeInit",
            "GameComponentUtility.StartedNewGame",
            "GameComponentUtility.LoadedGame",
            "FactionManager.FactionManagerTick",
            "Thing.TickLong",
            "Thing.TickRare",
            "Thing.Tick",
            "Thing.TickInterval",
            "the inner ThingComp tick methods:",
            "CompTick",
            "CompTickInterval",
            "CompTickRare",
            "CompTickLong",
            "WorldObject.Tick",
            "WorldObject.TickInterval",
            "WorldObjectComp.CompTick",
            "WorldObjectComp.CompTickInterval",
            "ThingComp.CompTick*",
            "WorldObject.Tick, WorldObject.TickInterval",
            "ThingComp.CompTickInterval",
            "ThingComp.CompTickRare",
            "ThingComp.CompTickLong",
            "WorldObjectComp.PostDestroy",
            "WorldObjectComp.PostMyMapRemoved",
            "WorldObjectComp.PostMapGenerate",
            "ThingOwner.DoTick",
            "PostExposeData",
            "PostMake",
            "PostRemove",
            "Destroy",
            "ThingComp lifecycle methods that are not tick methods but may still throw:",
            "Initialize",
            "PostMapInit",
            "PostSpawnSetup",
            "PostDeSpawn",
            "PostDestroy",
            "Thing",
            "ThingOwner",
            "WorldObject",
            "ThingComp"
        };
    }
}
